# Generated by Django 5.0.1 on 2024-01-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('date', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_link', models.CharField(choices=[('factory', 'Завод'), ('retail network', 'Розничная сеть'), ('entrepreneur', 'Индивидуальный предприниматель')], max_length=30, verbose_name='звено сети')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Уровень звена')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading_network.link', verbose_name='Поставщик')),
                ('products', models.ManyToManyField(to='trading_network.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Торговое звено',
                'verbose_name_plural': 'Торговые звенья',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('num_house', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_network.link', verbose_name='Торговое звено')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
